const { Pool } = require('pg');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });

async function seedDb() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });

  try {
    const client = await pool.connect();
    
    const code = `
      // Autonomous Healing Transformation generated by Sunder
      if (payload.cost_usd !== undefined) {
        payload.amount = payload.cost_usd;
        delete payload.cost_usd;
      }
    `;

    const query = `
      INSERT INTO transformer_functions (source_pipeline, target_pipeline, transformation_code, is_active)
      VALUES ('shopify_orders', 'snowflake_analytics', $1, true)
    `;
    
    await client.query(query, [code]);
    
    console.log('✅ Database seeded with the Sunder Healing Transformer!');
    client.release();
  } catch (err) {
    console.error('❌ Failed to seed database:', err.message);
  } finally {
    await pool.end();
  }
}

seedDb();
